apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort          # Important: makes it accessible outside Minikube
  selector:
    app: flask            # must match the label in your deployment.yaml
  ports:
    - port: 5000          # internal container port
      targetPort: 5000    # same as container port
      nodePort: 30007     # public port on EC2

